### ISSUE TITLE
ofxtools requires Python 3.7+ (instead of documented 3.4+)

### ISSUE THREAD

**Issue by diablodale** [csingley/ofxtools#60]
ofxtools requires Python 3.7+ due to the API call ` datetime.fromisoformat()`
I recommend the documentation/dependencies be updated to match the actual requirement.

https://github.com/csingley/ofxtools/blob/4c5eb73cc0feabe89e4c865e71e230387b74b1b1/ofxtools/ofxhome.py#L102

This API is only available in Python 3.7+ as https://docs.python.org/3/whatsnew/3.7.html#datetime

## Setup
Ubuntu 16.04
Python 3.5.2 managed by apt
ofxtools 0.8.0 via pip3

## Repo

1. `ofxget -n fidelity`

## Result

```
Traceback (most recent call last):
  File "/home/dale/.local/bin/ofxget", line 9, in <module>
    load_entry_point('ofxtools==0.8.0', 'console_scripts', 'ofxget')()
  File "/home/dale/.local/lib/python3.5/site-packages/ofxtools/Client.py", line 1001, in main
    args = merge_config(config, args)
  File "/home/dale/.local/lib/python3.5/site-packages/ofxtools/Client.py", line 866, in merge_config
    lookup = ofxhome.lookup(config[server]["ofxhome_id"])
  File "/home/dale/.local/lib/python3.5/site-packages/ofxtools/ofxhome.py", line 59, in lookup
    attrs = {e.tag: reader.get(e.tag, _read)(e) for e in etree}
  File "/home/dale/.local/lib/python3.5/site-packages/ofxtools/ofxhome.py", line 59, in <dictcomp>
    attrs = {e.tag: reader.get(e.tag, _read)(e) for e in etree}
  File "/home/dale/.local/lib/python3.5/site-packages/ofxtools/ofxhome.py", line 102, in _read_date
    text = datetime.datetime.fromisoformat(text)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

## Expected

The following is expected results, it was achieved by the same setup and repo except Python 3.7.1 on Ubuntu 18.04

```
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:NONE
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:b0df1563-c547-4602-9be9-0670ba81a8a3

<OFX><SIGNONMSGSRQV1><SONRQ><DTCLIENT>20190430143932.848[0:GMT]</DTCLIENT><USERID>redacted</USERID><USERPASS>anonymous00000000000000000000000</USERPASS><LANGUAGE>ENG</LANGUAGE><FI><ORG>fidelity.com</ORG><FID>7776</FID></FI><APPID>QWIN</APPID><APPVER>2700</APPVER></SONRQ></SIGNONMSGSRQV1></OFX>
```

**Comment by csingley** [comment]
Sorry about that.  This leads to the larger question of why Travis CI has been passing these builds on Python 3.4 - 3.6.

Dearly as I'd love to drop support for anything below 3.7 (so we'd get to use ordered class attributes, dataclasses, and many other goodies) for the time being I'm committed to support back to 3.4.

I'll just replace `fromisoformat()` with `strptime()` and focus on what's wrong with the CI build setup.

Thanks for reporting; let me know if you find any more.

**Comment by csingley** [comment]
Fixed in [37c76ed](https://github.com/csingley/ofxtools/commit/37c76edc1b287ce74ceda0e66717f9bccc751c32)
The gap in test coverage within `ofxtools.ofxhome` that allowed this to transpire has been plugged.

**Comment by diablodale** [comment]
Hi. Just tested this 0.8.1 release from pip. The error I reported above is gone. :-)

However, there is a change in behavior that makes 0.8.1 incompatible with 0.8.0. Is this your intention?
The new version *requires* scan,prof,acctinfo,stmt,or tax1099.
The previous version assumed stmt for my case cases. For example:

v0.8.0
`ofxget -i 111222333 -s 20190401 fidelity` worked

v0.8.1
`ofxget -i 111222333 -s 20190401 fidelity` fails with error
`ofxget: error: argument request: invalid choice: 'fidelity' (choose from 'scan', 'prof', 'acctinfo', 'stmt', 'tax1099')`

**Comment by csingley** [comment]
My apologies for not answering earlier; I missed your comment.

Yes, it is my intention that the first positional argument is mandatory, interpreted as a command.  It makes the code implementation much nicer and easier to debug... plus, if you're familiar with the OFX spec, there's a direct correspondence between the command options and STMTRQ, PROFRQ, ACCTINFORQ, etc.

You can expect the `ofxget stmt <servernick>` syntax will remain stable.

If you're building something around that assumption, though, you might want to drop me an email.  The ofxget script is currently very much in "move fast and break things" mode.  For example you might notice that since you reported this bug, I've upped the Python version requirement to 3.6+.  Not to mention that pretty much the entirety of the OFX Home database is now available locally in master, without need to make an API call out.

Drop me a line and and I can try to cut a release that you can pin to, if that is your requirement.  I'm adding a bunch of features and fixing several bugs, but that kind of moving target is no fun to code against.

**Comment by diablodale** [comment]
Got it. No worries or dependency coordination need at this time :-)
